### ISSUE TITLE
Missing "return" in clean task in README.md

### ISSUE THREAD

**Issue by neyric** [ThoughtWorksStudios/node-aws-lambda#6]
Just missing the return in the clean task, but this was messing the deploy task...
````js
gulp.task('clean', function(cb) {
  return del(['./dist', './dist.zip'], cb);
});
````

Cheers

**Comment by wpc** [comment]
hi, @neyric:

Thank you for pointing it out. This is due to "del" v2.0 changed to promise type of api and do not accept callback anymore.  I will update the  README.
